channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=23.0.1
- pip:
  - mlflow<3,>=2.2
  - attrs==21.4.0
  - cffi==1.15.0
  - colorama==0.4.4
  - defusedxml==0.7.1
  - dill==0.3.6
  - fsspec==2023.3.0
  - googleapis-common-protos==1.56.4
  - jax==0.4.6
  - jaxlib==0.4.6
  - numpy==1.22.4
  - packaging==23.0
  - pandas==1.3.5
  - pillow==9.2.0
  - protobuf==3.20.3
  - pydot==1.4.2
  - pygments==2.14.0
  - requests==2.28.0
  - scipy==1.9.3
  - tensorflow==2.11.0
name: mlflow-env
